DeCharla/DeCharlApp/urls.py
from django.urls import path
from . import views

app_name = 'DeCharlApp'

urlpatterns = [
    path('', views.index_GoRoom, name='index_GoRoom'),
    path('Settings/', views.settings, name='settings'),
    path('Help/', views.page_help, name='help'),
    path('JsonRoom', views.room_json, name='jsonRoom'),
    path('Logout/', views.logout),
    path('<str:room>/', views.showRoom, name='showRoom'),
]

DeCharla/DeCharla/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/DeCharla/')),
    path('DeCharla/', include('DeCharlApp.urls')),
    path('admin/', admin.site.urls),
]

DeCharla/DeCharlApp/models.py
from django.db import models
from django.utils import timezone


# -- Vamos a crear los modelos de la aplicación DeCharla


class Room(models.Model):

    roomName = models.CharField(max_length=50, primary_key=True)

    class Meta:
        verbose_name = "Room"
        verbose_name_plural = "Rooms"

    def __str__(self):
        return self.roomName


class Key(models.Model):

    key             = models.CharField(max_length=20, primary_key=True)

    class Meta:
        verbose_name = "Key"
        verbose_name_plural = "Keys"
        
    def __str__(self):
        return self.key


# Vamos a relacionar las tablas de roomMessage y user.
# Un usuario puede tener muchos comentarios, pero un comentario solo puede tener un usuario.
# Por lo que la relación es: 1 user -> N RoomComment.
class User(models.Model):

    userName   = models.CharField(max_length=50, default='Anónimo')
    sizeFont   = models.IntegerField(default=12)
    font       = models.CharField(max_length=50, default='Arial')
    key        = models.ForeignKey(Key, on_delete=models.CASCADE, related_name='cookie', blank=True, null=True)
    session    = models.CharField(max_length=150, primary_key=True)

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"
        ordering = ["-userName"]

    def __str__(self):
        return self.userName

# -- Hay que relacionar las tablas Room y RoomComment.
# -- Una sala puede tener muchos comentarios por lo que relacionamos las tablas
# -- como: 1 Room -> N RoomComment.
class RoomMessage(models.Model):

    room        = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='comments', blank=True, null=True)
    content     = models.TextField()
    photo       = models.BooleanField(default=False)
    messageDate = models.DateTimeField(default=timezone.now)
    user        = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments', blank=True, null=True)

    class Meta:
        verbose_name = "Message"
        verbose_name_plural = "Messages"
        ordering = ["-messageDate"]

    def __str__(self):
        return self.content


class RoomAccess(models.Model):

	room             = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='access')
	userName         = models.ForeignKey(User, on_delete=models.CASCADE, related_name='access')
	lastAccessDate   = models.DateTimeField()

	class Meta:
		verbose_name = "Last Access"
		verbose_name_plural = "Last Accesses"
		ordering = ["-lastAccessDate"]

	def __str__(self):
		return self.lastAccessDate

DeCharla/DeCharlApp/forms.py
from django import forms
from .models import RoomMessage


# -- Aquí vamos a poner los formularios de la práctica.


class FormSearchRoom(forms.Form):
    roomName = forms.CharField(
        label='Nombre de la sala',
        widget=forms.TextInput(attrs={
            'id': 'roomName',
            'class': 'form-control mb-2',
            'style': 'width:90%',
            'placeholder': 'Sala',
            'required': 'required',
            'oninvalid': "this.setCustomValidity('Por favor introduzca una palabra')"
        })
    )


class FormCreateMessage(forms.ModelForm):
    class Meta:
        model = RoomMessage
        fields = ['content', 'photo']
        widgets = {
            'content': forms.Textarea(attrs={
                'id': 'inputMessage',
                'class': 'col-12',
                'cols': 40,
                'rows': 1,
            }),
            'photo': forms.CheckboxInput(attrs={
                'class': 'photoinput'
            }),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['content'].label = ''
        self.fields['photo'].label = ''

DeCharla/DeCharlApp/views.py
# -- IMPORTS
import xml.etree.ElementTree as ET
import io

from django.views.decorators.csrf import csrf_exempt

from .XMLMessagesParse import XMLContentParse

from django.utils import timezone
from django.http import HttpResponse, Http404, JsonResponse, HttpResponseNotAllowed, HttpResponseRedirect
from .models import Room, User, RoomMessage, RoomAccess
from .forms import FormSearchRoom, FormCreateMessage
from django.shortcuts import render, redirect


def parametersOfRooms():
    # -- En esta funcion lo que estamos haciendo son los bucles que nos va a indicar cuantos mensajes
    # -- De texto hay asi como cuantos mensajes de foto hay, para ponerlo en la página web, en el pie de página.

    total_messages = 0
    total_photos = 0
    rooms = Room.objects.all()

    for room in rooms:
        room_messages = RoomMessage.objects.filter(room=room)
        total_messages = total_messages + room_messages.filter(photo=0).count()
        total_photos = total_photos + room_messages.filter(photo=1).count()

    return total_messages, total_photos


def serve_mainPage(request):

    # -- A esta funcion vamos a acceder si nos han solicitado / con un GET.
    rooms = Room.objects.all()
    messages = RoomMessage.objects.all()
    user = User.objects.get(session=request.COOKIES['idUser'])
    form_SearchRoom = FormSearchRoom()
    total_messages, total_photos = parametersOfRooms()

    roomLastMessages = {}  # -- room: hola number:

    for room in rooms:
        # -- First, ya que la tabla se encuentra ordenada por fecha
        last_access = RoomAccess.objects.filter(room=room, userName=user).first()
        if last_access:
            newNumberMessages = RoomMessage.objects.filter(room=room,
                                                           messageDate__gt=last_access.lastAccessDate).count()
        else:
            # -- Cuando no ha entrado nunca a la sala le sale que tiene todos los mensajes pendientes.
            newNumberMessages = RoomMessage.objects.filter(room=room).count()

        roomLastMessages[room] = newNumberMessages

    context = {
        'rooms': rooms,
        'messages': messages,
        'user': user,
        'form_SearchRoom': form_SearchRoom,
        'total_messages': total_messages,
        'total_photos': total_photos,
        'roomLastMessages': roomLastMessages,
    }
    return render(request, 'DeCharlApp/showRooms.html', context=context)


def index_GoRoom(request) -> HttpResponse:
    # -- En esta funcion vamos a enseñar cuáles son las salas que están
    # -- creadas, muestra todas, asi como, si es un POST, nos va a llevar a una sala, tanto si no está creada como
    # -- si lo está.

    # -- Analizamos primero si es un GET
    if request.method == 'GET':
        return serve_mainPage(request)
    elif request.method == 'POST':
        return processFormRoom(request)
    else:
        return HttpResponseNotAllowed(['GET', 'POST'])


def serve_roomPage(request, room):

    form_Message = FormCreateMessage()
    form_SearchRoom = FormSearchRoom()
    sala = Room.objects.get(roomName=room)
    user = User.objects.get(session=request.COOKIES['idUser'])
    message = RoomMessage.objects.filter(room=room)
    total_messages, total_photos = parametersOfRooms()

    # -- Quiero guardar el roomAccess, crear una nueva entrada cada vez que hace un get
    room_access = RoomAccess(room=sala, userName=user, lastAccessDate=timezone.now())
    room_access.save()

    context = {
        'room': sala,
        'user': user,
        'messages': message,
        'form_Message': form_Message,
        'form_SearchRoom': form_SearchRoom,
        'rooms': Room.objects.all(),
        'total_messages': total_messages,
        'total_photos': total_photos,
    }
    return render(request, 'DeCharlApp/showRoom.html', context)


def processXMLMessages(request, room):

    # -- En esta funcion lo que hacemos es si nos llega un PUT, procesa el mensaje.
    content_type = request.META.get('CONTENT_TYPE').lower()

    if content_type == 'application/xml' or content_type == 'text/xml':
        xml_body = request.body

        # -- Crear un objeto StringIO o BytesIO para almacenar los datos XML en memoria
        stream = io.BytesIO(xml_body)

        # -- Procesamos el XML
        parser = XMLContentParse(stream)
        newMessages = parser.getMessages()
        for message in newMessages:
            room = Room.objects.get(roomName=room)
            user = User.objects.get(session=request.COOKIES['idUser'])
            print(message)
            newMessage = RoomMessage.objects.create(room=room, user=user, photo=message['isimg'],
                                                    content=message['content'])

            newMessage.save()

        # Devolver una respuesta exitosa si se procesa correctamente
        return serve_roomPage(request, room.roomName)

@csrf_exempt
def showRoom(request, room):
    # -- Mostramos la sala que nos pasan por parametro.
    # -- Vamos a gestionar la llegada de un mensaje a la sala
    # -- Tanto si lo hace con un POST como si lo hace con un PUT
    # -- Si es un GET entonces simplemente mostramos la sala.

    # Yo voy a hacer get sin hacer un try-except porque sé que si o si el usuario
    # siempre va a existir si no, directamente no hubiese podido entrar a una sala y mandar
    # un mensaje (eso lo controlamos con el MiddleWare

    if request.method == 'GET':
        return serve_roomPage(request, room)
    elif request.method == 'POST':
        return createMessage(request, room)
    elif request.method == 'PUT':
        return processXMLMessages(request, room)
    else:
        return HttpResponseNotAllowed(['GET', 'POST', 'PUT'])


def settings(request):
    # -- En esta funcion vamos a especificar cuando se nos envie un POST con él
    # -- formulario de configuración, que es lo que queremos hacer.
    # -- Si se envia un GET, vamos a mostrar la plantilla de configuración.

    if request.method == 'GET':
        form_searchRoom = FormSearchRoom()
        total_messages, total_photos = parametersOfRooms()
        user = User.objects.get(session=request.COOKIES['idUser'])

        context = {
            'form_SearchRoom': form_searchRoom,
            'rooms': Room.objects.all(),
            'total_messages': total_messages,
            'total_photos': total_photos,
            'user': user,
        }
        return render(request, 'DeCharlApp/settings.html', context=context)

    elif request.method == 'POST':
        return updateUserSettings(request)

    else:
        return HttpResponseNotAllowed(['GET', 'POST'])


def page_help(request):

    # -- Pagina de ayuda, no podemos recibir nada mas que un GET.

    form_SearchRoom = FormSearchRoom()
    total_messages, total_photos = parametersOfRooms()
    user = User.objects.get(session=request.COOKIES['idUser'])
    context = {
        'user': user,
        'help': help,
        'form_SearchRoom': form_SearchRoom,
        'rooms': Room.objects.all(),
        'total_messages': total_messages,
        'total_photos': total_photos,
    }
    return render(request, 'DeCharlApp/help.html', context=context)


def createMessage(request, room):
    # -- A esta función llegamos a través de un POST, sirve para crear un mensaje.

    form = FormCreateMessage(request.POST)  # -- Esto le va a asignar cada uno de los campos que están en la request

    if form.is_valid():
        try:
            actualRoom = Room.objects.get(roomName=room)
            user = User.objects.get(session=request.COOKIES['idUser'])
            message = form.save()
            message.room = actualRoom
            message.user = user
            message.photo = True if 'photo' in request.POST else False
            message.save()

            source = '/DeCharla/' + actualRoom.roomName
            return redirect(source)

        except Room.DoesNotExist:

            return Http404('La sala no existe')

def processFormRoom(request):

    form = FormSearchRoom(request.POST)  # -- Esto le va a asignar cada uno de los campos que están en la request
    if form.is_valid():
        roomName = form.cleaned_data['roomName']
        room, created = Room.objects.get_or_create(roomName=roomName)
        source = '/DeCharla/' + room.__str__()
        return redirect(source)


def updateUserSettings(request):

    # -- Ha elegido el nombre
    if ('userName' in request.POST) and ('button' in request.POST):
        userName = request.POST['userName']
        user = User.objects.get(session=request.COOKIES['idUser'])
        user.userName = userName
        user.save()

        return serve_mainPage(request)

    # -- Ha elegido el tipo de letra además del tamaño
    elif ('font' in request.POST) and ('size' in request.POST) and ('button' in request.POST):
        font = request.POST['font']
        size = request.POST['size']
        user = User.objects.get(session=request.COOKIES['idUser'])
        user.font = font
        user.sizeFont = size
        user.save()

        return serve_mainPage(request)

    else:
        return HttpResponse('(Error 422) Petición rechazada, el formato es incorrecto.',
                            status=422, reason='Unprocessable Entity')


def room_json(request):
    if request.method == 'GET':
        if 'jsonRoom' in request.GET:
            try:
                # -- Se obtienen los mensajes de la sala indicada en el path
                room = Room.objects.get(roomName=request.GET['jsonRoom'])
                messages = RoomMessage.objects.filter(room=room)

                # -- Creación de una lista de diccionarios, donde cada diccionario guarda la info de cada mensaje
                message_list = []
                for message in messages:

DeCharla/templates/DeCharlApp/basic.html
<!DOCTYPE html>

{% load static %}

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'DeCharlApp/favicon.png' %}">
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'DeCharlApp/css/main.css' %}">
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
          crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
            crossorigin="anonymous"></script>
    <title>DeCharla: chat</title>
</head>
<body>
    <!--Cabecera -->
    <nav id="Banner"class="navbar navbar-expand-lg navbar-dark py-lg-1">
        <div class="container-fluid">
            <a class="navbar-brand text-white" href="{% url 'DeCharlApp:index_GoRoom' %}">
                <img src="{% static 'DeCharlApp/favicon.png' %}" alt="DeCharla" style="height: 2em;"> DeCharla
            </a>
        </div>
    </nav>
    <!-- Barra de navegacion menú -->
    <nav class="navbar navbar-expand-lg py-lg-1" style="background-color: #e3f2fd;">
        <div class="container-fluid">
            <!-- Barra menú solo para dispositivos pequeños -->
            <span id="smallMenu" class="navbar-brand d-lg-none">Menú</span>
            <button id="buttonSmallMenu" class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!-- Opciones menú-->
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav mb-2 mb-lg-0">
                    {% for i in '0123'|make_list %}
                        <li class="nav-item
                            {% cycle '/DeCharla/' '/DeCharla/Settings/' '/DeCharla/Help/' '/admin/' as path %}
                            {% cycle 'Principal' 'Configuración' 'Ayuda' 'Admin Site' as page %}">
                            {% if request.path != path %}
                                <a class="nav-link text-expanded" href="{{ path }}">
                                    {{ page }}
                                </a>
                            {% endif %}
                        </li>
                    {% endfor %}
                    <form method="GET" action="/DeCharla/Logout/">
                        {% csrf_token %}
                        <button class="Btn submit" name="buttonlogout" value="Logout" type="submit">
                            <div class="sign">
                                <svg viewBox="0 0 512 512">
                                    <path d="M377.9 105.9L500.7 228.7c7.2 7.2 11.3 17.1 11.3 27.3s-4.1 20.1-11.3 27.3L377.9 406.1c-6.4 6.4-15 9.9-24 9.9c-18.7 0-33.9-15.2-33.9-33.9l0-62.1-128 0c-17.7 0-32-14.3-32-32l0-64c0-17.7 14.3-32 32-32l128 0 0-62.1c0-18.7 15.2-33.9 33.9-33.9c9 0 17.6 3.6 24 9.9zM160 96L96 96c-17.7 0-32 14.3-32 32l0 256c0 17.7 14.3 32 32 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32l-64 0c-53 0-96-43-96-96L0 128C0 75 43 32 96 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32z"></path>
                                </svg>
                            </div>
                        </button>
                    </form>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Cuerpo principal de la pagina -->
    <div class="row m-0 col-12">
        <!-- Barra lateral derecha -->
        <aside class="col-lg-3 col-md-12 order-lg-2 order-md-1" id="sidebar">
            <div class="px-4 pt-4">
                <ul class="nav justify-content-center">
                    <h6 class="pt-4 pb-3 px-4 mb-4 border-bottom text-md-center text-sm-center col-12" id="barratittle">
                      <span class="opacity-75"> Bienvenido {{ user.userName }} !<br></span>
                      <span class="subtext opacity-75"> Escribe una sala para entrar o créala: </span>
                    </h6>
                    <nav id="searchRoom" class="nav flex-column align-items-start mb-sm-au">
                        <form action="/DeCharla/" method="POST" class="d-md-inline">
                            {% csrf_token %}
                            {{ form_SearchRoom }}
                            <input type="submit" class="btn btn-primary btn-sm" name="button" value="Buscar Sala">
                        </form>
                    </nav>
                </ul>
            </div>
        </aside>
        <div id="contenido_principal" class="col-lg-9 col-md-12 order-lg-1 order-md-2"> <!--"flex-fill-->
            {% block content %}
            <!-- Aquí va el contenido principal de la página -->
            {% endblock %}
        </div>

        <!-- Pie de página -->
        <div class="wrapper border col order-md-3 order-lg-3">
            <footer class="footer">
                <br>
                <p>DeCharla <img src="{% static 'DeCharlApp/favicon.png' %}" alt="DeCharla" style="height: 1em;"></p>
                <div class="loader">
                  <div class="loader__circle"></div>
                  <div class="loader__circle"></div>
                  <div class="loader__circle"></div>
                  <div class="loader__circle"></div>
                    <p style="padding-left: 50px;">Salas totales: {{ rooms|length }} |
                        Total mensajes: {{ total_messages }} |
                        Total de fotos: {{ total_photos }}
                    </p>
                </div>
                <p>&copy; 2023</p>
            </footer>
        </div>
    </div>

    <!-- Dynamic Room -->
    <!-- Lo ponemos aquí para garantizar que el js se ejecute después de que todos los elementos estén en el DOM -->
    <script src="{% static 'DeCharlApp/dynamicRoomScript.js' %}"></script>
</body>
</html>

DeCharla/templates/DeCharlApp/dynamicRoom.html
{% load static %}

<!-- Button trigger modal -->
<form class="m-0 col-lg-3 col-sm-6 mt-lg-0 mt-sm-3" method="GET" action="/DeCharla/JsonRoom">
  <button id="btnOpenModal" class="cssbuttons-io-button col-12 px-3" type="button"
          data-bs-toggle="modal" data-bs-target="#dynamicRoom"> Sala dinámica
    <div class="icon">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
        <path fill="none" d="M0 0h24v24H0z"></path>
        <path fill="currentColor" d="M16.172 11l-5.364-5.364 1.414-1.414L20 12l-7.778 7.778-1.414-1.414L16.172 13H4v-2z"></path>
      </svg>
    </div>
  </button>
</form>

<!-- Modal, dynamic room -->
<div class="modal fade" id="dynamicRoom" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      <!-- Titulo de sala y botón JSON -->
      <div class="modal-header col-12">
        <h2 class="col-5">Bienvenido a la sala <strong><em>{{ room.roomName }}</em></strong> </h2>
        <form class="m-0 col-5 mt-lg-0" method="GET" action="/DeCharla/JsonRoom">
          <button class="cssbuttons-io-button col-12 px-3" name="jsonRoom" type="submit" value="{{ room.roomName }}"> JSON
            <div class="icon">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
                <path fill="none" d="M0 0h24v24H0z"></path>
                <path fill="currentColor" d="M16.172 11l-5.364-5.364 1.414-1.414L20 12l-7.778 7.778-1.414-1.414L16.172 13H4v-2z">
                </path>
              </svg>
            </div>
          </button>
        </form>
        <button type="button" class="btn-close col-2 mx-2" data-bs-dismiss="modal" aria-label="Close">

        </button>
      </div>
      <!-- Cuerpo de mensajes de la sala -->
      <div id="messages-container" class="modal-body chat-container" data-room-name="{{ room.roomName }}"></div>
      <!-- Caja para introducir mensajes y/o cerrar la sala dinámica -->
      <div class="modal-footer">
        <form method="POST" action="/DeCharla/{{ room.roomName }}/" id="messageForm" class="col-12" id="messageForm">
          {% csrf_token %}
          <div class="input-wrapper col-12" style="font-family: {{ user.font }};">
            {{ form_Message }}
            <div class="row p-4">
              <label class="checkbox col-4 mx-lg-5 mx-md-8">
                <input id="checkbox-input" type="checkbox" name="photo">
                <span class="checkmark"></span>
                <span class="text">Incluye foto</span>
              </label>
              <button class="cssbuttons-io-button col-lg-6 col-sm-12 px-3" name="button" type="submit" value="Enviar"> Enviar mensaje
                <div class="icon">
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
                    <path fill="none" d="M0 0h24v24H0z"></path>
                    <path fill="currentColor" d="M16.172 11l-5.364-5.364 1.414-1.414L20 12l-7.778 7.778-1.414-1.414L16.172 13H4v-2z">
                    </path>
                  </svg>
                </div>
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<!--
<div class="row mb-4 col-12">

  </div>
  <div>
  <div class="chat-container my-3">
-->

DeCharla/templates/DeCharlApp/key_form.html
{% load static %}

<html>
<head>
    <meta charset="UTF-8">
    <title>Indentificación</title>
    <link rel="stylesheet" type="text/css" href="{% static 'DeCharlApp/css/main.css' %}">
</head>
<style>
    body {
        background-color: #00204b;
        margin: 150;
    }

    .form-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 50vh;
        margin: 0;
    }

    .imagen {
        height: 1em;
        filter: blur(2px);
        display: flex;
        justify-content: center;
        align-items: center;
    }

</style>
<body>
    {% if isError401 %}
        <div class="form-title"><span>Error 401 - contraseña mal</span></div>
    {% endif %}
    <p class="title-2"><span>Bienvenido a DeCharla</span></p>
     <br>
    <p class="imagen"><img src="{% static 'DeCharlApp/favicon.png' %}" alt="DeCharla" width="100"></p>
    <div class="form-container">
        <form method="POST" class="form">
            {% csrf_token %}
            <div class="form-title"><span>¿Contraseña antes de</span></div>
            <div class="title-2"><span>ENTRAR?</span></div>
            <section class="bg-stars">
                <span class="star"></span>
                <span class="star"></span>
                <span class="star"></span>
                <span class="star"></span>
            </section>

            <div class="input-container">
                <input class="input-pwd" type="password" name="key" placeholder="Introduce la contraseña">
            </div>
            <button type="submit" class="submit" name="button" value="key">
                <span class="sign-text">Entrar</span>
            </button>
        </form>
    </div>
</body>
</html>

DeCharla/templates/DeCharlApp/messageRoom.html
<span class="message-name">{{ message.user.userName }}</span>
<span class="message-date">{{ message.messageDate }}</span>
{% if message.photo %}
  <div class="m-5">
    <div class="message-photo">
      <img id="photo" class="img-fluid" src="{{ message.content }}" alt="URL errónea, no se puede mostrar la foto">
    </div>
  </div>
{% else %}
  <div class="message-content" style="font-family: {{ user.font }};">{{ message.content }}</div>
{% endif %}

DeCharla/templates/DeCharlApp/showRoom.html
{% extends "DeCharlApp/basic.html" %}
{% load static %}

{% block content %}
<div class="card">
  <div class="row mb-4 col-12">
    <h2 class="col-lg-6 col-sm-12">Bienvenido a la sala <strong><em>{{ room.roomName }}</em></strong> </h2>
    <form class="m-0 col-lg-3 col-sm-6 mt-lg-0 mt-sm-3" method="GET" action="/DeCharla/JsonRoom">
      <button class="cssbuttons-io-button col-12 px-3" name="jsonRoom" type="submit" value="{{ room.roomName }}"> JSON
        <div class="icon">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
            <path fill="none" d="M0 0h24v24H0z"></path>
            <path fill="currentColor" d="M16.172 11l-5.364-5.364 1.414-1.414L20 12l-7.778 7.778-1.414-1.414L16.172 13H4v-2z">
            </path>
          </svg>
        </div>
      </button>
    </form>
    {% include "DeCharlApp/dynamicRoom.html" %}
  </div>
  <div class="chat-container my-3">
    {% if messages %}
      {% for message in messages %}
        {% if message.user.userName == user.userName %}
          <div class="message-bubble realUser">
            {% include "DeCharlApp/messageRoom.html" %}
          </div>
        {% else %}
          <div class="message-bubble otherUser">
            {% include "DeCharlApp/messageRoom.html" %}
          </div>
        {% endif %}
      {% endfor %}
    {% else %}
    <p>No hay mensajes en esta sala</p>
    {% endif %}
  </div>
  <form method="POST" action="/DeCharla/{{ room.roomName }}/" class="col-12" id="messageForm">
    {% csrf_token %}
    <div class="input-wrapper col-12" style="font-family: {{ user.font }};">
      {{ form_Message }}
      <div class="row p-4">
        <label class="checkbox col-4 mx-lg-5 mx-md-8">
          <input type="checkbox" name="photo">
          <span class="checkmark"></span>
          <span class="text_check">Incluye foto</span>
        </label>
        <button class="cssbuttons-io-button col-lg-6 col-sm-12 px-3" name="button" type="submit" value="Enviar"> Enviar mensaje
          <div class="icon">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
              <path fill="none" d="M0 0h24v24H0z"></path>
              <path fill="currentColor" d="M16.172 11l-5.364-5.364 1.414-1.414L20 12l-7.778 7.778-1.414-1.414L16.172 13H4v-2z">
              </path>
            </svg>
          </div>
        </button>
      </div>
    </div>
  </form>
</div>

{% endblock %}